### ISSUE TITLE
Need to print a warning and continue if we can't get to ipmi for some reason

### ISSUE THREAD

**Issue by mabott** [Qumulo/snmp-agent-app#11]
[root@ada-server snmp-agent-app-ipmi-power-trap]# python agent.py
Starting agent
Exception in thread Thread-1:
Traceback (most recent call last):
 File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
   self.run()
 File "agent.py", line 313, in run
   self.check_cluster_status()
 File "agent.py", line 276, in check_cluster_status
   self.check_power(ipmi_server, node_id=list(ipmi_servers).index(ipmi_server))
 File "agent.py", line 235, in check_power
   for PS in power_states['FAIL']:
TypeError: list indices must be integers, not str

**Comment by mabott** [comment]
Fix merged to master
