### ISSUE TITLE
Exception when a PS is seen as fixed

### ISSUE THREAD

**Issue by mabott** [Qumulo/snmp-agent-app#12]
(snmp_agent) mbottMBP:snmp_agent mbott$ !509
sudo -E python agent.py
Password:
Starting agent
NOTIFICATION: PS2 in qumulo-3 failed
Sending trap
Sending email
Failed to send email (Subject: [ALERT] Qumulo Power Supply Failure qumulo-3) ((535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials v68sm4870715pfv.85 - gsmtp'))
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "agent.py", line 313, in run
    self.check_cluster_status()
  File "agent.py", line 276, in check_cluster_status
    self.check_power(ipmi_server, node_id=list(ipmi_servers).index(ipmi_server))
  File "agent.py", line 255, in check_power
    message = PS + " in node " + node_id + " power back to normal"
TypeError: cannot concatenate 'str' and 'int' objects

^CShutting down
(snmp_agent) mbottMBP:snmp_agent mbott$

**Comment by mabott** [comment]
Fix merged to master
