### ISSUE TITLE
Exception in get_cluster_state if API response is null

### ISSUE THREAD

**Issue by mabott** [Qumulo/snmp-agent-app#13]
```(snmp_agent) mbottMBP:snmp_agent mbott$ sudo -E python agent.py
Starting agent
NOTIFICATION: PS2 in qumulo-3 failed
Sending trap
Sending email
Failed to send email (Subject: [ALERT] Qumulo Power Supply Failure qumulo-3) ((535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials a9sm10748817pfe.147 - gsmtp'))
WARNING: Unexpected response to <function list_nodes at 0x106a799b0>: 'NoneType' object has no attribute 'data'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "agent.py", line 320, in run
    self.check_cluster_status()
  File "agent.py", line 286, in check_cluster_status
    self.check_nodes()
  File "agent.py", line 196, in check_nodes
    self.client.get_cluster_state()
  File "/Users/mbott/github/snmp_agent/qumulo_client.py", line 93, in get_cluster_state
    self.offline_nodes = [ s for s in self.cluster_state if s['node_status'] == 'offline' ]
TypeError: 'NoneType' object is not iterable
```

**Comment by mabott** [comment]
Fix merged to master
