### ISSUE TITLE
Send a trap if the agent can't reach any nodes

### ISSUE THREAD

**Issue by mabott** [Qumulo/snmp-agent-app#7]
```
mbottMBP:snmp_agent mbott$ SNMP_AGENT_EMAIL_ACCT=some_email@somecompany.com SNMP_AGENT_EMAIL_PWD='password' sudo -E /usr/bin/python agent.py
Problem connecting to the REST server: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
Warning: Creating unverified HTTPS Context!
Starting agent
NOTIFICATION: PS2 in qumulo-3 failed
Sending trap
Sending email
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "agent.py", line 310, in run
    self.check_cluster_status()
  File "agent.py", line 276, in check_cluster_status
    self.check_nodes()
  File "agent.py", line 196, in check_nodes
    self.client.get_cluster_state()
  File "/Users/mbott/github/snmp_agent/qumulo_client.py", line 86, in get_cluster_state
    self.cluster_state = self.get_api_response(qumulo.rest.cluster.list_nodes)
  File "/Users/mbott/github/snmp_agent/qumulo_client.py", line 83, in get_api_response
    return response_object.data
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by mabott** [comment]
```
Starting agent
Exception in thread Thread-1:
Traceback (most recent call last):
 File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
   self.run()
 File "agent.py", line 299, in run
   self.check_cluster_status()
 File "agent.py", line 262, in check_cluster_status
   self.check_nodes()
 File "agent.py", line 193, in check_nodes
   self.client.get_cluster_state()
 File "/root/Qumulo_snmp/snmp-agent-app-master/qumulo_client.py", line 71, in get_cluster_state
   self.cluster_state = self.get_api_response(qumulo.rest.cluster.list_nodes)
 File "/root/Qumulo_snmp/snmp-agent-app-master/qumulo_client.py", line 67, in get_api_response
   return response_object.data
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by mabott** [comment]
Fix merged with master
